#second round sequences 4/27

library(stringi)



#mdoified compareHap for ths purpose
compareHap3<- function(file, master,start1,stop1) {
  print(file)
  #inputs a chromatogram file and outputs the list of matches with the master list and the sequence that was a match
  sangerobj <- readsangerseq(MD17_18Jul17_26M_col1) #read in file
  
  #cut and add combined string
  basecalls <- makeBaseCalls(sangerobj)
  pri <- primarySeq(basecalls, string = 'TRUE')
  sec <- secondarySeq(basecalls, string = 'TRUE')
  cutpri = substr(pri,start1,stop1) 
  cutsec = substr(sec,start1,stop1)
  combined = addPriSeq3(cutpri,cutsec)
  print(combined)
  #look for matches within the master list supplied to function
  match = MODcheckMasterList7(MD17_18Jul17_26M_col1seq,master)
  print(match)
  return (match)
}


MODcheckMasterList7 <- function(newseq, master) {
  matchesList = data.frame()
  len = dim(master)[1]
  count = 1
  for (i in 6903:7021) {
    print("in")
    found = FALSE
    overlap = overlapIsTrue(newseq,master[i,1])
    
    found = (stri_detect_fixed(master[i,1],newseq, case_insensitive = TRUE) |stri_detect_fixed(newseq, master[i,1], case_insensitive = TRUE) | overlap )
    
    if (found == TRUE) {
      matchesList[count,1]= master[i,1]
      matchesList[count,2]= master[i,2]
      matchesList[count,3]= master[i,3]
      print(i)
      print("match found")
      
      print(count)
    }
    
  }
  count = 1+count
  
  return(matchesList)
}


#test 1 MD 26M
MD17_18Jul17_26M_col1 = "C:/Users/amw346/Desktop/NE111216MD26/MD17_18Jul17-26M colony 1 T7F2-SP6 kdr R.ab1"
MD17_18Jul17_26M_col1seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
compareHap3(MD17_18Jul17_26M_col1, newCombinedNoGapAllAdded7021, start1= 732,stop1 =1069)
MODcheckMasterList7(MD17_18Jul17_26M_col1seqredo,newCombinedNoGapAllAdded7021)

kdrhis1 = newCombinedNoGapAllAdded7021[6904,1]
b = pairwiseAlignment(kdrhis1,MD17_18Jul17_26M_col1seqredo)
writePairwiseAlignments(b)
6904
6934
#26M nomatch
MD17_18Jul17_26M_col2seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MD17_18Jul17_26M_col1seqredo = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
NE16_09Feb17_11F_col1seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_11F_col1seq,newCombinedNoGapAllAdded7021)
MD17_18Jul17_26_col2
MD17_18Jul17_26_col3

NE16_09Feb17_12F_col1seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col1seq,newCombinedNoGapAllAdded7021)
#match kdr 6 

NE16_09Feb17_12F_col2seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col2seq,newCombinedNoGapAllAdded7021)
#kdr 6 

NE16_09Feb17_12F_col3seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col3seq,newCombinedNoGapAllAdded7021)
#kdr6

NE16_09Feb17_16M_col1seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16M_col1seq,newCombinedNoGapAllAdded7021)
#kdr-his1

NE16_09Feb17_16M_col2seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16M_col2seq,newCombinedNoGapAllAdded7021)
#kdrhis1

NE16_09Feb17_16M_col4seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16M_col4seq,newCombinedNoGapAllAdded7021)
#kdrhis1


#fuzzymatchretest
filefuzzymatch = "C:/Users/amw346/Desktop/fliesUTNM/NE16_09Feb17-11F kdrFL-MdSCR7 s kdrFL.ab1"
compareHap(filefuzzymatch,newCombinedNoGapAllAdded7021)
#noomatches
