#second round sequences 4/27

library(stringi)



#mdoified compareHap for ths purpose
compareHap3<- function(file, master,start1,stop1) {
  print(file)
  #inputs a chromatogram file and outputs the list of matches with the master list and the sequence that was a match
  sangerobj <- readsangerseq(NE16_09Feb17_16F_col2) #read in file
  
  #cut and add combined string
  basecalls <- makeBaseCalls(sangerobj)
  pri <- primarySeq(basecalls, string = 'TRUE')
  sec <- secondarySeq(basecalls, string = 'TRUE')
  cutpri = substr(pri,start1,stop1) 
  cutsec = substr(sec,start1,stop1)
  combined = addPriSeq3(cutpri,cutsec)
  print(combined)
  #look for matches within the master list supplied to function
  match = MODcheckMasterList7(MD17_18Jul17_26M_col1seq,master)
  print(match)
  return (match)
}


MODcheckMasterList7 <- function(newseq, master) {
  matchesList = data.frame()
  len = dim(master)[1]
  count = 1
  for (i in 6903:7021) {
    print("in")
    found = FALSE
    overlap = overlapIsTrue(newseq,master[i,1])
    
    found = (stri_detect_fixed(master[i,1],newseq, case_insensitive = TRUE) |stri_detect_fixed(newseq, master[i,1], case_insensitive = TRUE) | overlap )
    
    if (found == TRUE) {
      matchesList[count,1]= master[i,1]
      matchesList[count,2]= master[i,2]
      matchesList[count,3]= master[i,3]
      print(i)
      print("match found")
      
      print(count)
    }
    
  }
  count = 1+count
  
  return(matchesList)
}
#fuzzymatchretest
filefuzzymatch = "C:/Users/amw346/Desktop/fliesUTNM/NE16_09Feb17-11F kdrFL-MdSCR7 s kdrFL.ab1"
compareHap(filefuzzymatch,newCombinedNoGapAllAdded7021)
#noomatches



#test 1 MD 26M
MD17_18Jul17_26M_col1 = "C:/Users/amw346/Desktop/NE111216MD26/MD17_18Jul17-26M colony 1 T7F2-SP6 kdr R.ab1"
MD17_18Jul17_26M_col1seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
compareHap3(MD17_18Jul17_26M_col1, newCombinedNoGapAllAdded7021, start1= 732,stop1 =1069)
MODcheckMasterList7(MD17_18Jul17_26M_col1seqredo,newCombinedNoGapAllAdded7021)

kdrhis1 = newCombinedNoGapAllAdded7021[6904,1]
b = pairwiseAlignment(kdrhis1,MD17_18Jul17_26M_col1seqredo)
writePairwiseAlignments(b)
6904
6934


#26M nomatch
MD17_18Jul17_26M_col2seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MD17_18Jul17_26M_col1seqredo = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"

MD17_18Jul17_26_col2
MD17_18Jul17_26_col3

#testing of Cloned Sequences against 118 sequences at end of newCombinednOgAPaLLADDED
#second round
MD17_18Jul17_26M_col1seq= "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(MD17_18Jul17_26M_col1seq,newCombinedNoGapAllAdded)
#n0match
MODcheckMasterList5(MD17_18Jul17_26M_col1seq, newCombinedNoGapAllAdded)
#cloests match kdr2 also with 4 mismatches kdr 6 ad v32
g = pairwiseAlignment(MD17_18Jul17_26M_col1seq, newCombinedNoGapAllAdded[6918,1])
writePairwiseAlignments(g)
MODcheckMasterList5(MD17_18Jul17_26M_col2seq, newCombinedNoGapAllAdded)
#closest match: kdr 2 <3

MD17_18Jul17_26_col4seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGCTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCCTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList5(MD17_18Jul17_26_col4seq,newCombinedNoGapAllAdded)

NE16_09Feb17_11F_col1seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_11F_col4seq,newCombinedNoGapAllAdded7021)
#kdr-his1

NE16_09Feb17_11F_col3seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCTTGTGGTAAGTTGACGTGGCCGAAACTGCTCTCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList5(NE16_09Feb17_11F_col3seq,newCombinedNoGapAllAdded)
p= pairwiseAlignment(NE16_09Feb17_11F_col3seq, newCombinedNoGapAllAdded[6945,1])
writePairwiseAlignments(p)

#fail- cloest match 6945 v3

NE16_09Feb17_11F_col4seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGTGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCTTGTGGTAAGTTGACGTGGCCGAAACTGCTCTCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCCTAATCTTTCCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList5(NE16_09Feb17_11F_col4seq,newCombinedNoGapAllAdded)
p= pairwiseAlignment(NE16_09Feb17_11F_col4seq, NE16_09Feb17_11F_col3seq)
writePairwiseAlignments(p)
#fail- cloests match 6972 v54

nchar(NE16_09Feb17_11F_col1seq)
nchar(NE16_09Feb17_11F_col3seq)
nchar(NE16_09Feb17_11F_col4seq)
NE_11F_3 = substr(NE16_09Feb17_11F_col3seq,1,339)
combo13 = addPriSeq3(NE16_09Feb17_11F_col1seq, NE_11F_3)
combo14 = addPriSeq3(NE16_09Feb17_11F_col1seq, NE16_09Feb17_11F_col4seq)
sangerobj <- readsangerseq("C:/Users/amw346/Desktop/fliesUTNM/NE16_09Feb17-11F kdrFL-MdSCR7 s kdrFL.ab1") #read in file
index = clipIndex2(sangerobj) #cut off all Ns at the end

#cut and add combined string
basecalls <- makeBaseCalls(sangerobj)
pri <- primarySeq(basecalls, string = 'TRUE')
sec <- secondarySeq(basecalls, string = 'TRUE')
cutpri = substr(pri,20,index) 
cutsec = substr(sec,20,index)
combined = addPriSeq3(cutpri,cutsec)
print(combined)
NE16_09Feb17_11Finput = combined
u = pairwiseAlignment(NE16_09Feb17_11Finput, combo13)
writePairwiseAlignments(u)
j = pairwiseAlignment(NE16_09Feb17_11Finput, combo14)
writePairwiseAlignments(j)

v54his1= newCombinedNoGapAllAdded[68,1]
v3his1 = newCombinedNoGapAllAdded[41,1]
b = pairwiseAlignment(NE16_09Feb17_11Finput, v54his1)
writePairwiseAlignments(b)
p = pairwiseAlignment(NE16_09Feb17_11Finput, v3his1)
writePairwiseAlignments(p)
#compared added col sequences to input, col1 +col3 was closer to input, compared input to his1.v3 adn his1/v54 from 
#database and v3 was closer 
v = pairwiseAlignment(NE16_09Feb17_11F_col4seq,NE16_09Feb17_11F_col3seq)
writePairwiseAlignments(v)
#difference between  col4 and col3 is a deletion and two mismatches
v2 = pairwiseAlignment(newCombinedNoGapAllAdded[6945,1],newCombinedNoGapAllAdded[6972,1])
writePairwiseAlignments(v2)
#differernce is deletion and several mismatch
#if had to guess would say its his1 v3



NE16_09Feb17_12F_col1seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col1seq,newCombinedNoGapAllAdded7021)
#match kdr 6 

NE16_09Feb17_12F_col2seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col2seq,newCombinedNoGapAllAdded7021)
#kdr 6 

NE16_09Feb17_12F_col3seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col3seq,newCombinedNoGapAllAdded7021)
#kdr6

NE16_09Feb17_16M_col1seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16M_col1seq,newCombinedNoGapAllAdded7021)
#kdr-his1

NE16_09Feb17_16M_col2seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16M_col2seq,newCombinedNoGapAllAdded7021)
#kdrhis1

NE16_09Feb17_16M_col4seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16M_col4seq,newCombinedNoGapAllAdded7021)
#kdrhis1



#third round 
sink("C:/Users/amw346/Desktop/thirdround16F.txt")

NE16_09Feb17_16F_col2 = "C:/Users/amw346/Desktop/thirdround/NE16_09Feb17-16F colony 2 T7F2-SP6 kdr.ab1"
NE16_09Feb17_16F_col2seq = "GAATTTCACCGACTTCATGCACAGCTTCATGATTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGTATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGACCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCTCAACTTTATTCCGTCCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16F_col2seq,newCombinedNoGapAllAdded7021)
#kdrhis1

NE16_09Feb17_16F_col4 = "C:/Users/amw346/Desktop/thirdround/NE16_09Feb17-16F colony 4 T7F2-SP6 kdr.ab1"
NE16_09Feb17_16F_col4seq = "GAATTTCACCGACTTCATGCACAGCTTCATGACTGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATCATGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCACCCGTCGGAATAAATATATTTTACACTTATCACTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGACCATCCTTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_16F_col4seq, newCombinedNoGapAllAdded)
#kdrhis3

NE16_09Feb17_16F_col6 = "C:/Users/amw346/Desktop/thirdround/NE16_09Feb17-16F colony 6 T7F2-SP6 kdr.ab1"
MODcheckMasterList7(NE16_09Feb17_16F_col4seq, newCombinedNoGapAllAdded)
#failed sequence

NE16_09Feb17_12F_col6seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col6seq, newCombinedNoGapAllAdded)
#kdr6

NE16_09Feb17_12F_col4seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col4seq, newCombinedNoGapAllAdded)
#kdr6

NE16_09Feb17_12F_col5seq = "GAACTTCACCGACTTCATGCACAGCTTCATGATCGTGTTCCGAGTGCTGTGCGGAGAGTGGATCGAGTCCATGTGGGACTGCATGTATGTGGGCGATGTCAGCTGTATACCCTTCTTCTTGGCCACGGTCGTGATCGGCAATTTTGTGGTAAGTTGACGTGGCCGAAACTGCTCCCCCGCTCCCAGGATGGAGGCTTCTGATGGCCAATTAAAAAAAATTAAATCAACCTCTCTCTTTCTCTCTCTCTCAACTTTATTCCGTCCATCCGTTGCAGGTTCTTAATCTTTTCTTAGCTTTGCTTTTGTCCAACTTCGGTTCATCTAGTTTATCAGCCCC"
MODcheckMasterList7(NE16_09Feb17_12F_col5seq, newCombinedNoGapAllAdded)
#kdr6

sink()

